
credentials:
    twitter_credentials: "credentials/twitter_credential.json"
    google_drive_credentials: null
    is_twitter_elevated_access: false 
storage:
    gdrive_folder_id: null
    dump_to_google_drive: false
    local_folder: "/tmp/"
collector:
    task_id: "test"
    query: "test"
    max_results: null
    dump_batch_size: 1000
    start_time: null
    end_time: null
database:
    host: "localhost"
    database: "twitter"
    user: "postgres"
    password: "postgres"
    tables:
        tweets: true
        users: true
        media: true
        places: false