
credentials:
    twitter_credentials: "credentials/twitter_credentials.json"
    google_drive_credentials: null
storage:
    gdrive_folder_id: null
    dump_to_google_drive: false
    local_folder: "/tmp/"
collector:
    dump_batch_size: null
    start_time: null
    end_time: null

