
credentials:
    twitter_credentials: "credentials/twitter_credentials_academic.json"
    google_drive_credentials: "credentials/client_secrets.json"
    is_twitter_elevated_access: true
storage:
    gdrive_folder_id: "1xvHEH-O-VWF7gSeJ5HSo5HIOyiI1udqx"
    dump_to_google_drive: true 
    local_folder: "/tmp/"
collector:
    task_id: "biometria_eleicoes"
    query: "((biometria votar) OR (biometria eleicao) OR (biometria eleicoes) OR (biometria voto)) (-is:retweet -mentira -mentiras -falsas -falsos -falso -falsa -fake -fato)"
    max_results: null
    dump_batch_size: 1000
    start_time: "2021-01-01T00:00:00Z"
    end_time: null