
credentials:
    twitter_credentials: "credentials/twitter_credentials.json"
    google_drive_credentials: null
    is_twitter_elevated_access: false
storage:
    gdrive_folder_id: null
    dump_to_google_drive: true 
    local_folder: "/tmp/"
collector:
    task_id: "task_example"
    query: "example"
    max_results: null
    dump_batch_size: 1000
    start_time: null
    end_time: null

